# Generated by Django 3.0.7 on 2022-10-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터 생성 일시', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='데이터 수정 일시', verbose_name='수정 일시')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='randomstation.BaseModel')),
                ('name', models.CharField(help_text='지하철 역명', max_length=64, verbose_name='역명')),
                ('line', models.CharField(help_text='지하철 호선', max_length=24, verbose_name='호선')),
                ('order', models.IntegerField(help_text='순번', max_length=4, verbose_name='순번')),
            ],
            bases=('randomstation.basemodel',),
        ),
    ]
