# Generated by Django 3.0.7 on 2022-10-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, help_text='데이터 생성 일시', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(blank=True, help_text='데이터 수정 일시', verbose_name='수정 일시')),
                ('name', models.CharField(help_text='지하철 역명', max_length=64, verbose_name='역명')),
                ('line', models.CharField(help_text='지하철 호선', max_length=24, verbose_name='호선')),
                ('order', models.IntegerField(help_text='순번', verbose_name='순번')),
                ('fr_code', models.CharField(default='0', help_text='외부코드', max_length=10, verbose_name='외부코드')),
            ],
            options={
                'verbose_name': '지하철 역',
                'verbose_name_plural': '지하철 역 목록',
                'ordering': ['line'],
            },
        ),
    ]
