# Generated by Django 3.0.7 on 2022-10-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='데이터 생성 일시', verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='데이터 수정 일시', verbose_name='수정 일시'),
        ),
    ]
