# Generated by Django 3.0.7 on 2022-10-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomstation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fr_code',
            field=models.CharField(default='0', help_text='외부코드', max_length=10, verbose_name='외부코드'),
        ),
        migrations.AlterField(
            model_name='station',
            name='order',
            field=models.IntegerField(help_text='순번', verbose_name='순번'),
        ),
    ]
