# Generated by Django 3.0.7 on 2022-10-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomstation', '0002_auto_20221023_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='station',
            name='updated_at',
        ),
    ]
